name: Repository quality check

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

env:
  FORCE_COLOR: true

jobs:
  check:
    name: Readme check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read # Checkout only

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.19.0

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Check if any README was modified
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            README.md

      - name: Check URLs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pnpm run check-urls
