name: Check Resources to Add

on:
  pull_request:
    branches: [main]

jobs:
  check-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.head_ref }}

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }} || true

      - name: Install Node.js v24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        uses: ./.github/actions/pnpmCache

      - name: Checking if resources are sorted
        run: pnpm sort-resources --check

      - name: Validate URLs
        run: pnpm check-urls
